vvm
double vvm::rdx
1/dx, calculated from Config_VVM given by users.
Referenced by Bouyancy, vvm::PoissonSolver::cal_u, vvm::Init::Init2d, vvm::Turbulence::RKM_RKH.
double vvm::r2dx
1 / (2dx), calculated from Config_VVM given by users.
Referenced by Advection_thermo, Advection_zeta, vvm::Turbulence::RKM_RKH.
double vvm::rdz
1 / dz, calculated from Config_VVM given by users.
Referenced by vvm::Init::Init2d, vvm::PoissonSolver::pubarTop_pt, vvm::Turbulence::RKM_RKH.
double vvm::r2dz
1 / (2dz), calculated from Config_VVM given by users.
Referenced by Advection_qrVT, Advection_thermo, Advection_zeta, vvm::Turbulence::RKM_RKH.
double vvm::rdx2
1 / (dx^2), calculated from Config_VVM given by users.
Referenced by vvm::NumericalProcess::Diffusion, vvm::Turbulence::Hparam, vvm::Turbulence::Mparam.
double vvm::rdz2
1 / (dz^2), calculated from Config_VVM given by users.
Referenced by vvm::NumericalProcess::Diffusion, vvm::Turbulence::Hparam, vvm::Turbulence::Mparam.
int vvm::nx
Number of grid points in x direction, calculated from Config_VVM given by users.
Referenced by vvm::MicroPhysics::accretion, AddForcing, Advection_qrVT, Advection_thermo, Advection_zeta, allocateMemory, vvm::MicroPhysics::autoconversion, BoundaryProcess2D_all, BoundaryProcess2D_center, BoundaryProcess2D_westdown, Bouyancy, vvm::PoissonSolver::cal_u, vvm::PoissonSolver::cal_w, vvm::MicroPhysics::condensation, deallocate3DContinuousArray, vvm::NumericalProcess::Diffusion, vvm::MicroPhysics::evaporation, vvm::Turbulence::Hparam, vvm::Init::Init2d, vvm::PoissonSolver::InitPoissonMatrix, vvm::Turbulence::Mparam, vvm::MicroPhysics::NegativeValueProcess, vvm::Iteration::nextTimeStep, vvm::Output::output_precip, vvm::Output::output_qc, vvm::Output::output_qr, vvm::Output::output_qv, vvm::Output::output_th, vvm::Output::output_u, vvm::Output::output_w, vvm::Output::output_zeta, vvm::Iteration::pqc_pt, vvm::Iteration::pqr_pt, vvm::Iteration::pqv_pt, vvm::Iteration::pth_pt, vvm::PoissonSolver::pubarTop_pt, vvm::Iteration::pzeta_pt, vvm::Init::RandomPerturbation, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::TimeFilter, vvm::Iteration::TimeMarching, vvm::Iteration::updateMean.
int vvm::nz
Number of grid points in z direction, calculated from Config_VVM given by users.
Referenced by vvm::MicroPhysics::accretion, AddForcing, Advection_qrVT, Advection_thermo, Advection_zeta, allocateMemory, vvm::MicroPhysics::autoconversion, BoundaryProcess1D_center, BoundaryProcess2D_all, BoundaryProcess2D_center, BoundaryProcess2D_westdown, Bouyancy, vvm::PoissonSolver::cal_u, vvm::PoissonSolver::cal_w, vvm::MicroPhysics::condensation, vvm::NumericalProcess::Diffusion, vvm::MicroPhysics::evaporation, vvm::Turbulence::Hparam, vvm::Init::Init1d, vvm::Init::Init2d, vvm::PoissonSolver::InitPoissonMatrix, vvm::Turbulence::Mparam, vvm::MicroPhysics::NegativeValueProcess, vvm::Iteration::nextTimeStep, vvm::Output::output_qc, vvm::Output::output_qr, vvm::Output::output_qv, vvm::Output::output_th, vvm::Output::output_u, vvm::Output::output_w, vvm::Output::output_zeta, vvm::Iteration::pqc_pt, vvm::Iteration::pqr_pt, vvm::Iteration::pqv_pt, vvm::Output::printInit, vvm::Iteration::pth_pt, vvm::PoissonSolver::pubarTop_pt, vvm::Iteration::pzeta_pt, vvm::Init::RandomPerturbation, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::TimeFilter, vvm::Iteration::TimeMarching, vvm::Iteration::updateMean.
double vvm::dt
From Config_VVM given by users.
Referenced by vvm::MicroPhysics::accretion, AddForcing, Advection_qrVT, Advection_thermo, Advection_zeta, vvm::MicroPhysics::autoconversion, Bouyancy, vvm::MicroPhysics::evaporation, vvm::Turbulence::Hparam, vvm::Turbulence::Mparam, vvm::Turbulence::RKM_RKH, vvm::Iteration::TimeMarching.
double vvm::d2t
From Config_VVM given by users.
Referenced by vvm::MicroPhysics::accretion, AddForcing, Advection_qrVT, Advection_thermo, Advection_zeta, vvm::MicroPhysics::autoconversion, Bouyancy, vvm::NumericalProcess::Diffusion, vvm::MicroPhysics::evaporation, vvm::PoissonSolver::pubarTop_pt.
double vvm::dx
From Config_VVM given by users.
Referenced by vvm::PoissonSolver::cal_u, vvm::PoissonSolver::cal_w, vvm::Init::Init1d, vvm::Turbulence::RKM_RKH.
double vvm::dz
From Config_VVM given by users.
Referenced by vvm::PoissonSolver::cal_u, vvm::Init::Init1d, vvm::Init::Init2d, vvm::Output::printInit, vvm::Init::RandomPerturbation, vvm::Turbulence::RKM_RKH.
int vvm::XRANGE
From Config_VVM given by users.
int vvm::ZRANGE
From Config_VVM given by users.
double vvm::TIMEEND
From Config_VVM given by users.
Referenced by vvm::Iteration::TimeMarching.
int vvm::TIMEROUTPUTSIZE
From Config_VVM given by users.
Referenced by allocateMemory, vvm::Iteration::TimeMarching.
std::string vvm::outputpath
From Config_VVM given by users.
Referenced by vvm::Output::create_all_directory, vvm::Output::output_precip, vvm::Output::output_qc, vvm::Output::output_qr, vvm::Output::output_qv, vvm::Output::output_th, vvm::Output::output_u, vvm::Output::output_w, vvm::Output::output_zeta, vvm::Output::printInit.
int vvm::OUTPUTSTEP
From Config_VVM given by users.
Referenced by vvm::Iteration::TimeMarching.
double vvm::Kx
From Config_VVM given by users.
Referenced by vvm::NumericalProcess::Diffusion.
double vvm::Kz
From Config_VVM given by users.
Referenced by vvm::NumericalProcess::Diffusion.
double vvm::TIMETS
From Config_VVM given by users.
Referenced by vvm::NumericalProcess::TimeFilter.
double vvm::tolerance
From Config_VVM given by users.
Referenced by vvm::PoissonSolver::cal_w.
double vvm::GRAVITY
From Config_VVM given by users.
Referenced by Bouyancy, vvm::Init::Init1d, vvm::Turbulence::RKM_RKH.
double vvm::Cp
From Config_VVM given by users.
Referenced by vvm::MicroPhysics::condensation, vvm::MicroPhysics::evaporation, vvm::Init::Init1d.
double vvm::Cv
From Config_VVM given by users.
Referenced by vvm::Init::Init1d.
double vvm::Rd
From Config_VVM given by users.
Referenced by vvm::MicroPhysics::condensation, vvm::MicroPhysics::evaporation, vvm::Init::Init1d.
double vvm::Lv
From Config_VVM given by users.
Referenced by vvm::MicroPhysics::condensation, vvm::MicroPhysics::evaporation.
double vvm::P0
From Config_VVM given by users.
Referenced by vvm::MicroPhysics::condensation, vvm::MicroPhysics::evaporation, vvm::Init::Init1d.
double vvm::PSURF
From Config_VVM given by users.
Referenced by vvm::Init::Init1d.
double vvm::addforcingtime
From Config_VVM given by users.
Referenced by vvm::Init::Init2d, vvm::Iteration::TimeMarching.
int vvm::CASE
From Config_VVM given by users.
Referenced by vvm::Init::Init2d.
int vvm::step
The current time step.
Referenced by Advection_qrVT, Advection_thermo, Advection_zeta, Bouyancy, vvm::Iteration::TimeMarching.
double vvm::ubarTopp
The top boundary of the zonal wind for future time step. In the model design part, this is used to predict the mean top boundary of the zonal wind in the 9th governing equation.
Referenced by vvm::PoissonSolver::cal_u, vvm::Iteration::nextTimeStep, vvm::PoissonSolver::pubarTop_pt.
double vvm::ubarTop
The top boundary of the zonal wind for future time step. In the model design part, this is used to predict the mean top boundary of the zonal wind in the 9th governing equation.
Referenced by vvm::Init::Init2d, vvm::Iteration::nextTimeStep.
double vvm::ubarTopm
The top boundary of the zonal wind for future time step. In the model design part, this is used to predict the mean top boundary of the zonal wind in the 9th governing equation.
Referenced by vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::PoissonSolver::pubarTop_pt.
double* vvm::thb
Referenced by allocateMemory, deallocateMemory, vvm::Init::Init1d, vvm::Init::Init2d, vvm::Output::printInit, vvm::Turbulence::RKM_RKH, vvm::Iteration::updateMean.
double* vvm::thbm
Referenced by allocateMemory, deallocateMemory, vvm::Init::Init1d, vvm::Iteration::updateMean.
double* vvm::thb_zeta
Referenced by allocateMemory, deallocateMemory, vvm::Init::Init1d, vvm::Output::printInit, vvm::Iteration::updateMean.
double* vvm::rhou
Referenced by Advection_qrVT, Advection_thermo, Advection_zeta, allocateMemory, vvm::PoissonSolver::cal_u, vvm::PoissonSolver::cal_w, deallocateMemory, vvm::MicroPhysics::evaporation, vvm::Init::Init1d, vvm::PoissonSolver::InitPoissonMatrix, vvm::Iteration::pqr_pt, vvm::Output::printInit, vvm::PoissonSolver::pubarTop_pt.
double* vvm::rhow
Referenced by Advection_qrVT, Advection_thermo, Advection_zeta, allocateMemory, Bouyancy, vvm::PoissonSolver::cal_u, vvm::PoissonSolver::cal_w, deallocateMemory, vvm::Init::Init1d, vvm::Init::Init2d, vvm::PoissonSolver::InitPoissonMatrix, vvm::Iteration::pqr_pt, vvm::Output::printInit.
double* vvm::pib
Referenced by allocateMemory, vvm::MicroPhysics::condensation, deallocateMemory, vvm::MicroPhysics::evaporation, vvm::Init::Init1d, vvm::Output::printInit.
double* vvm::qvb
Referenced by allocateMemory, deallocateMemory, vvm::Init::Init1d, vvm::Init::Init2d, vvm::Output::printInit, vvm::Iteration::updateMean.
double* vvm::qvsb
Referenced by allocateMemory, deallocateMemory, vvm::Init::Init1d, vvm::Output::printInit.
double* vvm::pb
Referenced by allocateMemory, deallocateMemory, vvm::MicroPhysics::evaporation, vvm::Init::Init1d.
double* vvm::xi
Referenced by allocateMemory, vvm::PoissonSolver::cal_u, deallocateMemory.
double* vvm::uxi
Referenced by allocateMemory, vvm::PoissonSolver::cal_u, deallocateMemory.
double* vvm::thvb
Referenced by allocateMemory, Bouyancy, deallocateMemory, vvm::Init::Init1d, vvm::Iteration::updateMean.
double* vvm::thvbm
Referenced by allocateMemory, deallocateMemory, vvm::Init::Init1d, vvm::Iteration::updateMean.
double* vvm::z
Referenced by allocateMemory, deallocateMemory, vvm::Init::Init1d, vvm::Output::printInit, vvm::Init::RandomPerturbation.
double* vvm::lambda2
Referenced by allocateMemory, deallocateMemory, vvm::Init::Init1d, vvm::Turbulence::RKM_RKH.
double** vvm::zetap
Referenced by Advection_zeta, allocateMemory, BoundaryProcess2D_all, Bouyancy, vvm::PoissonSolver::cal_u, vvm::PoissonSolver::cal_w, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Iteration::pzeta_pt, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll.
double** vvm::zeta
Referenced by Advection_zeta, allocateMemory, deallocateMemory, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Output::output_zeta, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll.
double** vvm::zetam
Referenced by Advection_zeta, allocateMemory, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::NumericalProcess::timeFilterAll.
double** vvm::thp
Referenced by AddForcing, allocateMemory, BoundaryProcess2D_all, vvm::MicroPhysics::condensation, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::MicroPhysics::evaporation, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Iteration::pth_pt, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll, vvm::Iteration::updateMean.
double** vvm::th
Referenced by allocateMemory, deallocateMemory, getTHV, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Output::output_th, vvm::Iteration::pth_pt, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll.
double** vvm::thm
Referenced by allocateMemory, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Iteration::pth_pt, vvm::NumericalProcess::timeFilterAll.
double** vvm::u
Referenced by Advection_thermo, Advection_zeta, allocateMemory, BoundaryProcess2D_all, vvm::PoissonSolver::cal_u, deallocateMemory, vvm::Init::Init2d, vvm::Output::output_u, vvm::PoissonSolver::pubarTop_pt, vvm::Turbulence::RKM_RKH.
double** vvm::w
Referenced by Advection_thermo, Advection_zeta, allocateMemory, BoundaryProcess2D_all, vvm::PoissonSolver::cal_u, vvm::PoissonSolver::cal_w, deallocateMemory, vvm::Init::Init2d, vvm::Output::output_w, vvm::Iteration::pqr_pt, vvm::PoissonSolver::pubarTop_pt, vvm::Turbulence::RKM_RKH.
double** vvm::RKM
Referenced by allocateMemory, deallocateMemory, vvm::Turbulence::Mparam, vvm::Turbulence::RKM_RKH.
double** vvm::RKH
Referenced by allocateMemory, deallocateMemory, vvm::Turbulence::Hparam, vvm::Turbulence::RKM_RKH.
double** vvm::U_w
Referenced by Advection_zeta, allocateMemory, deallocateMemory.
double** vvm::W_u
Referenced by Advection_zeta, allocateMemory, deallocateMemory.
double* vvm::zetapcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::zetacont
Referenced by allocateMemory, deallocateMemory.
double* vvm::zetamcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::thpcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::thcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::thmcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::ucont
Referenced by allocateMemory, deallocateMemory.
double* vvm::wcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::init_th_forcingcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::RKMcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::RKHcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::U_wcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::W_ucont
Referenced by allocateMemory, deallocateMemory.
double** vvm::qvp
Referenced by AddForcing, allocateMemory, BoundaryProcess2D_all, vvm::MicroPhysics::condensation, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::MicroPhysics::evaporation, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Iteration::pqv_pt, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll, vvm::Iteration::TimeMarching, vvm::Iteration::updateMean.
double** vvm::qv
Referenced by allocateMemory, deallocateMemory, getTHV, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Output::output_qv, vvm::Iteration::pqv_pt, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll.
double** vvm::qvm
Referenced by allocateMemory, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Iteration::pqv_pt, vvm::NumericalProcess::timeFilterAll.
double** vvm::qcp
Referenced by vvm::MicroPhysics::accretion, allocateMemory, vvm::MicroPhysics::autoconversion, BoundaryProcess2D_all, vvm::MicroPhysics::condensation, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Iteration::pqc_pt, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll, vvm::Iteration::TimeMarching.
double** vvm::qc
Referenced by allocateMemory, Bouyancy, deallocateMemory, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Output::output_qc, vvm::Iteration::pqc_pt, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll.
double** vvm::qcm
Referenced by allocateMemory, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Iteration::pqc_pt, vvm::NumericalProcess::timeFilterAll.
double** vvm::qrp
Referenced by vvm::MicroPhysics::accretion, Advection_qrVT, allocateMemory, vvm::MicroPhysics::autoconversion, BoundaryProcess2D_all, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::MicroPhysics::evaporation, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Iteration::pqr_pt, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll, vvm::Iteration::TimeMarching.
double** vvm::qr
Referenced by Advection_qrVT, allocateMemory, Bouyancy, deallocateMemory, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Output::output_qr, vvm::Iteration::pqr_pt, vvm::Turbulence::RKM_RKH, vvm::NumericalProcess::timeFilterAll.
double** vvm::qrm
Referenced by Advection_qrVT, allocateMemory, deallocateMemory, vvm::NumericalProcess::DiffusionAll, vvm::Init::Init2d, vvm::Iteration::nextTimeStep, vvm::Iteration::pqr_pt, vvm::NumericalProcess::timeFilterAll.
double** vvm::evaporation
Referenced by allocateMemory, deallocateMemory, vvm::MicroPhysics::evaporation.
double** vvm::accretion
Referenced by vvm::MicroPhysics::accretion, allocateMemory, deallocateMemory.
double** vvm::autoconversion
Referenced by allocateMemory, vvm::MicroPhysics::autoconversion, deallocateMemory.
double** vvm::condensation
Referenced by allocateMemory, vvm::MicroPhysics::condensation, deallocateMemory.
double* vvm::precip
Referenced by allocateMemory, deallocateMemory, vvm::Output::output_precip, vvm::Iteration::pqr_pt.
double* vvm::qvpcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::qvcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::qvmcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::qcpcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::qccont
Referenced by allocateMemory, deallocateMemory.
double* vvm::qcmcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::qrpcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::qrcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::qrmcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::evaporationcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::accretioncont
Referenced by allocateMemory, deallocateMemory.
double* vvm::autoconversioncont
Referenced by allocateMemory, deallocateMemory.
double* vvm::condensationcont
Referenced by allocateMemory, deallocateMemory.
double*** vvm::dth_advect
Referenced by allocateMemory, deallocateMemory, vvm::Iteration::pth_pt.
double*** vvm::dth_buoyancy
Referenced by allocateMemory, Bouyancy, deallocateMemory.
double*** vvm::dzeta_advect
Referenced by Advection_zeta, allocateMemory, deallocateMemory.
double* vvm::dth_advectcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::dth_buoyancycont
Referenced by allocateMemory, deallocateMemory.
double* vvm::dzeta_advectcont
Referenced by allocateMemory, deallocateMemory.
double*** vvm::dqv_advect
Referenced by allocateMemory, deallocateMemory, vvm::Iteration::pqv_pt.
double*** vvm::dqc_advect
Referenced by allocateMemory, deallocateMemory, vvm::Iteration::pqc_pt.
double*** vvm::dqr_advect
Referenced by allocateMemory, deallocateMemory, vvm::Iteration::pqr_pt.
double*** vvm::dqr_VT
Referenced by Advection_qrVT, allocateMemory, deallocateMemory.
double* vvm::dqv_advectcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::dqc_advectcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::dqr_advectcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::dqr_VTcont
Referenced by allocateMemory, deallocateMemory.
double* vvm::t_advection
Referenced by allocateMemory, deallocateMemory, vvm::Iteration::TimeMarching.
double* vvm::t_poisson
Referenced by allocateMemory, deallocateMemory, vvm::Iteration::TimeMarching.
double* vvm::t_diffusion
Referenced by allocateMemory, deallocateMemory, vvm::Iteration::TimeMarching.
double* vvm::t_microphysics
Referenced by allocateMemory, deallocateMemory, vvm::Iteration::TimeMarching.
double* vvm::t_all
Referenced by allocateMemory, deallocateMemory, vvm::Iteration::TimeMarching.
Eigen::SparseMatrix<double> vvm::A
Referenced by vvm::PoissonSolver::cal_w, vvm::PoissonSolver::InitPoissonMatrix.
Eigen::SparseMatrix<double> vvm::G
Referenced by vvm::PoissonSolver::cal_u, vvm::PoissonSolver::InitPoissonMatrix.
double** vvm::init_th_forcing
Referenced by AddForcing, allocateMemory, deallocateMemory, vvm::Init::Init2d, vvm::Init::RandomPerturbation.
bool vvm::status_for_adding_forcing
Referenced by AddForcing, vvm::Iteration::TimeMarching.
vvm::vvm(const Config_VVM &config)
vvm constructor. Used to initialize the model.
References allocateMemory.
vvm::~vvm()
References deallocateMemory.
void vvm::deallocateMemory()
References accretion, accretioncont, autoconversion, autoconversioncont, condensation, condensationcont, deallocate2DContinuousArray, deallocate3DContinuousArray, dqc_advect, dqc_advectcont, dqr_advect, dqr_advectcont, dqr_VT, dqr_VTcont, dqv_advect, dqv_advectcont, dth_advect, dth_advectcont, dth_buoyancy, dth_buoyancycont, dzeta_advect, dzeta_advectcont, evaporation, evaporationcont, init_th_forcing, init_th_forcingcont, lambda2, pb, pib, precip, qc, qccont, qcm, qcmcont, qcp, qcpcont, qr, qrcont, qrm, qrmcont, qrp, qrpcont, qv, qvb, qvcont, qvm, qvmcont, qvp, qvpcont, qvsb, rhou, rhow, RKH, RKHcont, RKM, RKMcont, t_advection, t_all, t_diffusion, t_microphysics, t_poisson, th, thb, thb_zeta, thbm, thcont, thm, thmcont, thp, thpcont, thvb, thvbm, u, U_w, U_wcont, ucont, uxi, w, W_u, W_ucont, wcont, xi, z, zeta, zetacont, zetam, zetamcont, zetap, zetapcont.
Referenced by ~vvm.
void vvm::allocateMemory()
References accretion, accretioncont, allocate2DContinuousArray, allocate3DContinuousArray, autoconversion, autoconversioncont, condensation, condensationcont, dqc_advect, dqc_advectcont, dqr_advect, dqr_advectcont, dqr_VT, dqr_VTcont, dqv_advect, dqv_advectcont, dth_advect, dth_advectcont, dth_buoyancy, dth_buoyancycont, dzeta_advect, dzeta_advectcont, evaporation, evaporationcont, init_th_forcing, init_th_forcingcont, lambda2, nx, nz, pb, pib, precip, qc, qccont, qcm, qcmcont, qcp, qcpcont, qr, qrcont, qrm, qrmcont, qrp, qrpcont, qv, qvb, qvcont, qvm, qvmcont, qvp, qvpcont, qvsb, rhou, rhow, RKH, RKHcont, RKM, RKMcont, t_advection, t_all, t_diffusion, t_microphysics, t_poisson, th, thb, thb_zeta, thbm, thcont, thm, thmcont, thp, thpcont, thvb, thvbm, TIMEROUTPUTSIZE, u, U_w, U_wcont, ucont, uxi, w, W_u, W_ucont, wcont, xi, z, zeta, zetacont, zetam, zetamcont, zetap, zetapcont.
Referenced by vvm.
double *** vvm::allocate3DContinuousArray(int dim1, int dim2, int dim3, double *&contMemory)
Referenced by allocateMemory.
void vvm::deallocate3DContinuousArray(double ***array, double *contMemory)
References nx.
Referenced by deallocateMemory.
static double ** vvm::allocate2DContinuousArray(int rows, int cols, double *&contMemory)
Referenced by Advection_qrVT, Advection_thermo, Advection_zeta, allocateMemory.
static void vvm::deallocate2DContinuousArray(double **array, double *contMemory)
Referenced by Advection_qrVT, Advection_thermo, Advection_zeta, deallocateMemory.
void vvm::BoundaryProcess1D_center(double *var, int nz)
A member function that process the boundary of the 1D array where the varibles are at the center of the grid var an one dimensional array that should be put into boundary process.
References nz.
Referenced by vvm::Init::Init1d, vvm::Iteration::updateMean.
void vvm::BoundaryProcess2D_center(double **var, int nx, int nz)
A member function that process the boundary of the 2D array where the varibles are at the center of the grid var an two dimensional array that should be put into boundary process.
References nx, nz.
Referenced by Advection_qrVT, Advection_thermo, Advection_zeta, BoundaryProcess2D_all, vvm::PoissonSolver::cal_u, vvm::Init::Init2d, vvm::Iteration::pqc_pt, vvm::Iteration::pqr_pt, vvm::Iteration::pqv_pt, vvm::Iteration::pth_pt, vvm::Init::RandomPerturbation, vvm::Turbulence::RKM_RKH.
void vvm::BoundaryProcess2D_westdown(double **var, int nx, int nz)
A member function that process the boundary of the 2D array where the varibles are at the southwestern side of the grid var an two dimensional array that should be put into boundary process.
References nx, nz.
Referenced by BoundaryProcess2D_all, vvm::PoissonSolver::cal_w, vvm::Init::Init2d, vvm::Iteration::pzeta_pt.
void vvm::BoundaryProcess2D_all(vvm &model)
References BoundaryProcess2D_center, BoundaryProcess2D_westdown, nx, nz, qcp, qrp, qvp, thp, u, w, zetap.
Referenced by vvm::Iteration::TimeMarching.
void vvm::Advection_zeta(vvm &model)
A member function that do advection process to the vorticity (zeta) field. model the vvm object which is used to advect the vorticity field and put into it.
References allocate2DContinuousArray, BoundaryProcess2D_center, d2t, deallocate2DContinuousArray, dt, dzeta_advect, MINU, nx, nz, PLUS, r2dx, r2dz, rhou, rhow, step, u, U_w, w, W_u, zeta, zetam, zetap.
Referenced by vvm::Iteration::pzeta_pt.
void vvm::Advection_thermo(double **past, double **now, double **future, double ***dvar, vvm &model)
A member function that do advection process to the vorticity (zeta) field. previous an two dimensional array that the timestep is the previous one such as zetam, thm. now an two dimensional array that the timestep is now such as zeta, th. future an two dimensional array that the timestep is the future one such as zetap, thp. model the vvm object which is the model that will be used to do the diffusion (mainly the wind and the grid info).
References allocate2DContinuousArray, BoundaryProcess2D_center, d2t, deallocate2DContinuousArray, dt, MINU, nx, nz, PLUS, r2dx, r2dz, rhou, rhow, step, u, w.
Referenced by vvm::Iteration::pqc_pt, vvm::Iteration::pqr_pt, vvm::Iteration::pqv_pt, vvm::Iteration::pth_pt.
void vvm::Advection_qrVT(vvm &model)
References allocate2DContinuousArray, BoundaryProcess2D_center, d2t, deallocate2DContinuousArray, dqr_VT, dt, nx, nz, qr, qrm, qrp, r2dz, rhou, rhow, step.
Referenced by vvm::Iteration::pqr_pt.
void vvm::Bouyancy(vvm &model)
References d2t, dt, dth_buoyancy, getTHV, GRAVITY, nx, nz, qc, qr, rdx, rhow, step, thvb, zetap.
Referenced by vvm::Iteration::pzeta_pt.
void vvm::AddForcing(vvm &model)
References d2t, dt, init_th_forcing, nx, nz, qvp, status_for_adding_forcing, thp.
Referenced by vvm::Iteration::TimeMarching.