vvm::NumericalProcess
void vvm::NumericalProcess::Diffusion(double **var_in, double **var_out, vvm &model)
References vvm::d2t, vvm::Kx, vvm::Kz, vvm::nx, vvm::nz, vvm::rdx2, vvm::rdz2.
void vvm::NumericalProcess::DiffusionAll(vvm &model)
References vvm::qcm, vvm::qcp, vvm::qrm, vvm::qrp, vvm::qvm, vvm::qvp, vvm::thm, vvm::thp, vvm::zetam, vvm::zetap.
Referenced by vvm::Iteration::TimeMarching.
void vvm::NumericalProcess::TimeFilter(double **previous, double **now, double **future, vvm &model)
References vvm::nx, vvm::nz, vvm::TIMETS.
void vvm::NumericalProcess::timeFilterAll(vvm &model)
References vvm::qc, vvm::qcm, vvm::qcp, vvm::qr, vvm::qrm, vvm::qrp, vvm::qv, vvm::qvm, vvm::qvp, vvm::th, vvm::thm, vvm::thp, vvm::zeta, vvm::zetam, vvm::zetap.
Referenced by vvm::Iteration::TimeMarching.
void vvm::NumericalProcess::Nudge_theta(vvm &model)
References vvm::CRAD, vvm::dt, vvm::dz, vvm::nx, vvm::nz, vvm::thb_init, vvm::thp, vvm::z.
Referenced by vvm::Iteration::TimeMarching.
void vvm::NumericalProcess::Nudge_zeta(vvm &model)
References vvm::CRAD, vvm::dt, vvm::dz, vvm::nx, vvm::nz, vvm::z_zeta, vvm::zetap.
Referenced by vvm::Iteration::TimeMarching.
void vvm::NumericalProcess::Nudge_qv(vvm &model)
References vvm::dt, vvm::moisture_nudge_time, vvm::nx, vvm::nz, vvm::qv, vvm::qvb0, vvm::qvp.
Referenced by vvm::Iteration::TimeMarching.