vvm::PoissonSolver
Eigen::SparseMatrix<double> vvm::PoissonSolver::A
Eigen::SparseMatrix<double> vvm::PoissonSolver::G
void vvm::PoissonSolver::InitPoissonMatrix(vvm &model)
References vvm::A, vvm::G, vvm::nx, vvm::nz, vvm::rhou, vvm::rhow.
Referenced by main.
void vvm::PoissonSolver::cal_w(vvm &, int p=0, int i=0, int j=0)
References vvm::A, vvm::BoundaryProcess2D_westdown, vvm::dx, vvm::nx, vvm::nz, vvm::rhou, vvm::rhow, vvm::tolerance, vvm::w, vvm::zetap.
Referenced by main, vvm::Iteration::TimeMarching.
void vvm::PoissonSolver::cal_u(vvm &model)
References vvm::BoundaryProcess2D_center, vvm::dx, vvm::dz, vvm::G, vvm::nx, vvm::nz, vvm::rdx, vvm::rhou, vvm::rhow, vvm::u, vvm::ubarTopp, vvm::uxi, vvm::w, vvm::xi, vvm::zetap.
Referenced by main, vvm::Iteration::TimeMarching.
void vvm::PoissonSolver::pubarTop_pt(vvm &model)
References vvm::d2t, vvm::nx, vvm::nz, vvm::rdz, vvm::rhou, vvm::u, vvm::ubarTopm, vvm::ubarTopp, vvm::w.
Referenced by vvm::Iteration::TimeMarching.