vvm::MicroPhysics
void vvm::MicroPhysics::condensation(vvm &model)
References vvm::condensation, vvm::Cp, vvm::Lv, vvm::nx, vvm::nz, vvm::P0, vvm::pib, vvm::qcp, vvm::qvp, vvm::Rd, vvm::thp.
Referenced by vvm::Iteration::TimeMarching.
void vvm::MicroPhysics::autoconversion(vvm &model)
References vvm::autoconversion, vvm::d2t, vvm::dt, vvm::nx, vvm::nz, vvm::qcp, vvm::qrp.
Referenced by vvm::Iteration::TimeMarching.
void vvm::MicroPhysics::accretion(vvm &model)
References vvm::accretion, vvm::d2t, vvm::dt, vvm::nx, vvm::nz, vvm::qcp, vvm::qrp.
Referenced by vvm::Iteration::TimeMarching.
void vvm::MicroPhysics::evaporation(vvm &model)
References vvm::Cp, vvm::d2t, vvm::dt, vvm::evaporation, vvm::Lv, vvm::nx, vvm::nz, vvm::P0, vvm::pb, vvm::pib, vvm::qrp, vvm::qvp, vvm::Rd, vvm::rhou, vvm::thp.
Referenced by vvm::Iteration::TimeMarching.
void vvm::MicroPhysics::NegativeValueProcess(double **var, int nx, int nz)
References vvm::nx, vvm::nz.
Referenced by vvm::Iteration::pqc_pt, vvm::Iteration::pqr_pt, vvm::Iteration::pqv_pt, vvm::Iteration::TimeMarching.