Output
void Output::printInit(vvm &)
References dz, model, vvm::nz, OUTPUTPATH, vvm::pib, vvm::qvb, vvm::qvsb, vvm::rhou, vvm::rhow, vvm::thb, vvm::thb_zeta.
Referenced by main.
void Output::create_all_directory()
References OUTPUTPATH.
Referenced by main.
void Output::output_nc(int, vvm &)
References vvm::accretion, vvm::autoconversion, vvm::evaporation, model, vvm::nx, vvm::nz, OUTPUTPATH, vvm::precip, vvm::qc, vvm::qr, vvm::qrAcc, vvm::qv, vvm::qvb, vvm::qvsb, vvm::rhou, vvm::rhow, vvm::th, vvm::thb, vvm::u, vvm::w, vvm::zeta.
Referenced by Iteration::TimeMarching.
void Output::create_directory(std::string)