Init
void Init::Init1d(vvm &)
References vvm::BoundaryProcess1D_center, C_p, Cv, dz, GRAVITY, LoadFile, model, vvm::nz, P0, vvm::pb, vvm::pib, PSURF, vvm::qvb, vvm::qvsb, Rd, vvm::rhou, vvm::rhow, vvm::thb, vvm::thb_zeta, vvm::thbm, vvm::thvb, vvm::thvbm, vvm::tvb.
Referenced by main.
void Init::Init2d(vvm &)
References vvm::BoundaryProcess2D_center, vvm::BoundaryProcess2D_westdown, dz, model, vvm::nx, vvm::nz, vvm::qv, vvm::qvb, vvm::qvm, vvm::rdx, vvm::rdz, vvm::rhow, vvm::th, vvm::thb, vvm::thm, vvm::u, vvm::ubarTop, vvm::ubarTopm, vvm::w, vvm::zeta, vvm::zetam.
Referenced by main.
void Init::LoadFile(vvm &)
References vvm::BoundaryProcess1D_center, model, NZ, vvm::nz, vvm::pb, vvm::pib, vvm::qvb, vvm::qvsb, vvm::rhou, vvm::rhow, vvm::thb, vvm::thb_zeta, vvm::tvb.
Referenced by Init1d.
double Init::GetTB(int)
double Init::GetTHRAD(int, int)
double Init::GetTH(int, int)
double Init::GetQVB(int)