Iteration
void Iteration::pzeta_pt(vvm &)
References vvm::Advection_zeta, vvm::BoundaryProcess2D_westdown, vvm::Bouyancy, model, vvm::zetap.
Referenced by TimeMarching.
void Iteration::pth_pt(vvm &)
References vvm::Advection_thermo, vvm::BoundaryProcess2D_center, model, vvm::th, vvm::thm, vvm::thp.
Referenced by TimeMarching.
void Iteration::pqv_pt(vvm &)
References vvm::Advection_thermo, vvm::BoundaryProcess2D_center, microphysics, model, vvm::MicroPhysics::NegativeValueProcess, vvm::qv, vvm::qvm, vvm::qvp.
Referenced by TimeMarching.
void Iteration::pqc_pt(vvm &)
References vvm::Advection_thermo, vvm::BoundaryProcess2D_center, microphysics, model, vvm::MicroPhysics::NegativeValueProcess, vvm::qc, vvm::qcm, vvm::qcp.
Referenced by TimeMarching.
void Iteration::pqr_pt(vvm &)
References vvm::Advection_qrVT, vvm::Advection_thermo, vvm::BoundaryProcess2D_center, microphysics, model, vvm::MicroPhysics::NegativeValueProcess, vvm::nx, vvm::precip, vvm::qr, vvm::qrAcc, vvm::qrm, vvm::qrp, vvm::rhow, vvm::w.
Referenced by TimeMarching.
void Iteration::updateMean(vvm &)
References vvm::BoundaryProcess1D_center, model, vvm::nx, vvm::nz, vvm::qvb, vvm::qvp, vvm::thb, vvm::thb_zeta, vvm::thbm, vvm::thp, vvm::thvb, vvm::thvbm.
Referenced by TimeMarching.
void Iteration::TimeMarching(vvm &)
References vvm::MicroPhysics::accretion, vvm::MicroPhysics::autoconversion, vvm::BoundaryProcess2D_center, vvm::BoundaryProcess2D_westdown, vvm::PoissonSolver::cal_u, vvm::PoissonSolver::cal_w, vvm::MicroPhysics::condensation, vvm::Diffusion, DT, vvm::MicroPhysics::evaporation, microphysics, model, vvm::MicroPhysics::NegativeValueProcess, vvm::nx, vvm::nz, Output::output_nc, OUTPUTSTEP, poissonSolver, pqc_pt, pqr_pt, pqv_pt, pth_pt, vvm::PoissonSolver::pubarTop_pt, pzeta_pt, vvm::qc, vvm::qcm, vvm::qcp, vvm::qr, vvm::qrm, vvm::qrp, vvm::qv, vvm::qvm, vvm::qvp, vvm::th, vvm::thm, vvm::thp, TIMEEND, vvm::TimeFilter, vvm::u, vvm::ubarTop, vvm::ubarTopm, vvm::ubarTopp, vvm::um, updateMean, vvm::w, vvm::wm, vvm::zeta, vvm::zetam, vvm::zetap.
Referenced by main.