vvm::Turbulence
void vvm::Turbulence::RKM_RKH(vvm &model)
References vvm::BoundaryProcess2D_center, vvm::dt, vvm::dx, vvm::dz, vvm::GRAVITY, Hparam, vvm::lambda2, Mparam, vvm::nx, vvm::nz, vvm::qc, vvm::qcp, vvm::qr, vvm::qrp, vvm::qv, vvm::qvp, vvm::r2dx, vvm::r2dz, vvm::rdx, vvm::rdz, vvm::RKH, vvm::RKM, vvm::th, vvm::thb, vvm::thp, vvm::u, vvm::w, vvm::zeta, vvm::zetap.
Referenced by vvm::Iteration::TimeMarching.
void vvm::Turbulence::Mparam(vvm &model, double **var_now, double **var_future)
References vvm::dt, vvm::nx, vvm::nz, vvm::rdx2, vvm::rdz2, vvm::RKM.
Referenced by RKM_RKH.
void vvm::Turbulence::Hparam(vvm &model, double **var_now, double **var_future)
References vvm::dt, vvm::nx, vvm::nz, vvm::rdx2, vvm::rdz2, vvm::RKH.
Referenced by RKM_RKH.