vvm::Output
void vvm::Output::printInit(vvm &model)
References vvm::dz, vvm::nz, vvm::outputpath, vvm::pib, vvm::qvb, vvm::qvsb, vvm::rhou, vvm::rhow, vvm::thb, vvm::thb_zeta, vvm::z.
Referenced by main.
void vvm::Output::create_all_directory(vvm &model)
References vvm::outputpath.
Referenced by main.
void vvm::Output::create_directory(std::string path)
void vvm::Output::output_zeta(int step, vvm &model)
References vvm::nx, vvm::nz, vvm::outputpath, vvm::zeta.
Referenced by outputalltxt.
void vvm::Output::output_th(int step, vvm &model)
References vvm::nx, vvm::nz, vvm::outputpath, vvm::th.
Referenced by outputalltxt.
void vvm::Output::output_u(int step, vvm &model)
References vvm::nx, vvm::nz, vvm::outputpath, vvm::u.
Referenced by outputalltxt.
void vvm::Output::output_w(int step, vvm &model)
References vvm::nx, vvm::nz, vvm::outputpath, vvm::w.
Referenced by outputalltxt.
void vvm::Output::output_qv(int step, vvm &model)
References vvm::nx, vvm::nz, vvm::outputpath, vvm::qv.
Referenced by outputalltxt.
void vvm::Output::output_qc(int step, vvm &model)
References vvm::nx, vvm::nz, vvm::outputpath, vvm::qc.
Referenced by outputalltxt.
void vvm::Output::output_qr(int step, vvm &model)
References vvm::nx, vvm::nz, vvm::outputpath, vvm::qr.
Referenced by outputalltxt.
void vvm::Output::output_precip(int step, vvm &model)
References vvm::nx, vvm::outputpath, vvm::precip.
Referenced by outputalltxt.
void vvm::Output::outputalltxt(int step, vvm &model)
References output_precip, output_qc, output_qr, output_qv, output_th, output_u, output_w, output_zeta.
Referenced by vvm::Iteration::TimeMarching.