vvm::Init
void vvm::Init::Init1d(vvm &model)
References vvm::BoundaryProcess1D_center, vvm::Cp, vvm::Cv, vvm::dx, vvm::dz, vvm::GRAVITY, vvm::lambda2, vvm::nz, vvm::P0, vvm::pb, vvm::pib, vvm::PSURF, vvm::qvb, vvm::qvb0, vvm::qvsb, vvm::Rd, vvm::rhou, vvm::rhow, vvm::thb, vvm::thb_init, vvm::thb_zeta, vvm::thbm, vvm::thvb, vvm::thvbm, vvm::z, vvm::z_zeta.
Referenced by main.
void vvm::Init::Init2d(vvm &model)
References vvm::addforcingtime, vvm::BoundaryProcess2D_center, vvm::BoundaryProcess2D_westdown, vvm::CASE, vvm::dz, vvm::init_th_forcing, vvm::nx, vvm::nz, vvm::qc, vvm::qcm, vvm::qcp, vvm::qr, vvm::qrm, vvm::qrp, vvm::qv, vvm::qvb, vvm::qvm, vvm::qvp, vvm::rdx, vvm::rdz, vvm::rhow, vvm::th, vvm::thb, vvm::thm, vvm::thp, vvm::u, vvm::ubarTop, vvm::ubarTopm, vvm::w, vvm::zeta, vvm::zetam, vvm::zetap.
Referenced by main.
void vvm::Init::RandomPerturbation(vvm &model, int t, double min_range=-0.25, double max_range=0.25, double standard_deviation=1.)
References vvm::BoundaryProcess2D_center, vvm::dz, vvm::init_th_forcing, vvm::nx, vvm::nz, vvm::z.
Referenced by vvm::Iteration::TimeMarching.
double vvm::Init::GetTB(int i, vvm &model)
double vvm::Init::GetTHRAD(int i, int k, vvm &model)
double vvm::Init::GetTH(int i, int k, vvm &model)
double vvm::Init::GetQVB(int k, int dz)